name: RGB Cycle Daily

'on':
  #schedule:
    #- cron: '30 16 * * *'   # 日本時間 1:30
  workflow_dispatch:

jobs:
  post-rgb:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run RGB cycle script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python rgb_cycle.py
